[package]
name = "eon"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
publish = false

[dependencies]
eon-manifest = { path = "../eon-manifest" }
eon-workspace-protocol = { path = "../eon-workspace-protocol" }
libc = "=0.2.189"
orbit-protocol = { git = "https://github.com/Yazelix/eon-sessions.git", rev = "ea9fd28ce0908f218cf65d4e6df368f0a4e565f5" }
serde = { version = "=1.0.228", features = ["derive"] }
socket2 = "=0.6.5"
toml = { version = "=1.1.4", default-features = false, features = ["parse", "serde", "std"] }
